# ================================
# IDS/IPS Reverse Lookup Detector
# Configuration file
# ================================

api_keys:
  virustotal: "cebf11b47954aeb2eb4bf03064a14064ebb7678da58815b2d2bef19b38d3d483"
  aws_access_key: "your-aws-access-key"
  aws_secret_key: "your-aws-secret-key"

endpoints:
  virustotal: "https://www.virustotal.com/api/v3/"
  aws_endpoint: "https://route53.amazonaws.com/"

monitoring:
  interval_seconds: 60
  max_retries: 3
  timeout_seconds: 30
  alert_threshold: 5

aws:
  region: us-east-1
  route53_zones: []

logging:
  level: info
  output: stdout

docker:
  enabled: true
  container: "bind9"
  read_stdlogs: true       
  tail_files: false        
  files:
    - "/var/log/bind/bind.log"
    - "/var/log/named.log"

notifications:
  email:
    from_email: "alerts.doppel@gmail.com"  
    from_name:  "Doppel Alerts"             
    to:         "luseple738@gmail.com"     
    subject_prefix: "[Doppel]"
