# ================================
# IDS/IPS Reverse Lookup Detector
# Configuration file
# ================================

api_keys:
  cloudflare: "your-cloudflare-api-key"
  virustotal: "your-virustotal-api-key"
  aws_access_key: "your-aws-access-key"
  aws_secret_key: "your-aws-secret-key"
  digitalocean: "your-do-api-key"

endpoints:
  cloudflare: "https://api.cloudflare.com/client/v4/"
  virustotal: "https://www.virustotal.com/api/v3/"
  aws_endpoint: "https://route53.amazonaws.com/"
  digitalocean_endpoint: "https://api.digitalocean.com/v2/"

monitoring:
  interval_seconds: 60
  max_retries: 3
  timeout_seconds: 30
  alert_threshold: 5

cloudflare:
  api_key: "your-cloudflare-api-key"
  zones:
    - "zone-id-1"
    - "zone-id-2"

aws:
  region: "us-east-1"
  route53_zones:
    - "Z1234567890ABC"
    - "Z0987654321XYZ"

digitalocean:
  domains:
    - "example.com"
    - "yourdomain.com"

logging:
  level: "info"
  output: "console"
       

