services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config:/etc/bind
      - ./zones:/etc/bind/zones
      - ./logs:/var/log/bind
    environment:
      - TZ=America/New_York
    command: ["-c", "/etc/bind/named.conf", "-g"]
